flathub/org.DolphinEmu.dolphin-emu

appdata.xml
org.DolphinEmu.dolphin-emu.json

I've tested it superficially by playing wind waker.
There aren't any obvious regressions, the new feature to 
disable arbitrary mipmap detection works as intended.

Update to 5.0-8357 coinciding with the June 2018 progress report

---

forcexdg.patch
org.DolphinEmu.dolphin-emu.json

In some cases dolphin would try to use non xdg paths for its configuration files and subsequently be unable to write to them, causing it to crash or otherwise fail.
Fixes #18

Prevent dolphin from attempting to write non-standard conf files

---

appdata.xml
org.DolphinEmu.dolphin-emu.json

I have confirmed through personal testing that the bluetooth passthrough feature does work with this release. However, it requires the user to manually create a udev rule in the host machine as detailed in the dolphin documentation: https://wiki.dolphin-emu.org/index.php?title=USB_Passthrough#Linux
This is hardly ideal, but it's the way upstream recommends, and flatpak doesn't currently offer a means to improve it.

Update to 5.0-8987 for the September and October 2018 progress report

---

org.DolphinEmu.dolphin-emu.json

We also resize the svg in a hackish way using sed because f-b
complains that a 2048x2048 svg is too large and I couldn't get 
rsvg-convert to work properly. Could be the version in the runtime, will 
investigate when able.

Update to kde5.12

---

appdata.xml

It's empty, the rationale is that even though dolphin can be used to play violent games, it doesn't actually include any games. Games must be acquired separately and have their own rating systems.

Add content_rating tag to appdata file

---

org.DolphinEmu.dolphin-emu.json

Fixes build errors seen in #45 
https://flathub.org/builds/#/builders/27/builds/6143
```
flatpak-builder --download-only --no-shallow-clone --allow-missing-runtimes --state-dir=/srv/buildbot/sources /srv/buildbot/sources/.builddir org.DolphinEmu.dolphin-emu.json
in dir /srv/buildbot/worker/download-sources/build (timeout 3600 secs)
watching logfiles {}
argv: [b'flatpak-builder', b'--download-only', b'--no-shallow-clone', b'--allow-missing-runtimes', b'--state-dir=/srv/buildbot/sources', b'/srv/buildbot/sources/.builddir', b'org.DolphinEmu.dolphin-emu.json']
using PTY: True
Can't parse 'org.DolphinEmu.dolphin-emu.json': <data>:18:61: Parse error: unexpected character `,', expected character `]'
program finished with exit code 1
elapsedTime=0.039274
```

fix(build): remove dangling comma

---

nodirtyversion.patch
org.DolphinEmu.dolphin-emu.json

This changes the build number from the git hash to the one used by other platforms builds.
This allows the NetPlay session browser to match clients of the same version.

Fix version number for netplay

---

appdata.xml

This makes sure, that there is one entry for this app in `plasma-discover`, instead of two.

appdata: add <provides>

---

org.DolphinEmu.dolphin-emu.json

- kde5.15 allows us to upgrade to an fdo20.08 base without needing to manually build qt.
- libusb 1.0.23 was released last year but went unnoticed.

Bump dependencies

---

appdata.xml
org.DolphinEmu.dolphin-emu.json

While there wasn't a new Dolphin progress report, a new Beta version was released, which should warrant an update. The Dolphin developers noted this in their changelog:
> Hey everyone, we don't have a Dolphin Progress Report this month, but it's come to our attention that last month's build had some very annoying regressions. The "Real Wii Remote" option was instantly disconnecting Wii Remotes [...] Considering how many people use our beta builds [...], these regressions were unacceptable to leave unfixed. We're sorry to have to push an impromptu update, but these problems were severe enough that we felt it necessary to do so immediately.
I was personally having some issues with pairing Real Wiimotes, hopefully this will fix that.

Updated to 5.0-14095

---

org.DolphinEmu.dolphin-emu.yml

It's apparently necessary for some motion controllers
that aren't real wii remotes.

Build with DENABLE_EVDEV=ON

---

org.DolphinEmu.dolphin-emu.yml

We have two problems:
1. Dolphin is not compatible with Wayland (So it would crash)
2. Dolphin is crashing since socket=wayland isn't set
So I added this variable to foce X in XWayland and Dolphin can now start and emulating games.

Fixed Wayland Support

---

flathub.json
org.DolphinEmu.dolphin-emu.yml

flathub won't build for the 32bit arches anyway, this is superfluous.
Also the arm specific build options didn't do anything,
they're just a leftover from when we dropped arm in 2019.

Drop skiparches and arm specific build-options

---

org.DolphinEmu.dolphin-emu.yml

The steamdeck runs kde but has [some issues with the kde portal](https://github.com/flathub/org.DolphinEmu.dolphin-emu/issues/86#issuecomment-1113249128).
As a workaround we're crudely detecting the steamdeck using vendor
strings and setting `QT_QPA_PLATFORMTHEME=gtk3` until a fix comes.

Use gtk3 file chooser on steamdeck

---

org.DolphinEmu.dolphin-emu.appdata.xml
org.DolphinEmu.dolphin-emu.yml

flatpak-external-data-checker requires appdata.xml to be named org.DolphinEmu.dolphin-emu.appdata.xml to update the releases field.
The formatting changes are to stop f-e-d-c from changing indentation in dolphin-emu-wrapper.

Support auto update release version metadata

---

org.DolphinEmu.dolphin-emu.appdata.xml
org.DolphinEmu.dolphin-emu.yml

The dolphin update json now includes a release timestamp: https://github.com/dolphin-emu/www/pull/146

Automate release timestamp

---

org.DolphinEmu.dolphin-emu.appdata.xml

It seems that the German description translation was re-translated,  instead of using the already translated version from the Dolphin Homepage, which I have fixed in order to keep consistency.
I've also added a comment, so that future translators/contributors don't retranslate, but instead also just pull the content from the Dolphin homepage.

Fix German appstream description

---

org.DolphinEmu.dolphin-emu.appdata.xml
org.DolphinEmu.dolphin-emu.yml

Essentially https://github.com/flathub/org.DolphinEmu.dolphin-emu/pull/136 but without broken bluez update.
I tested performance of Super Mario Galaxy on Steam Deck, and this version improves it a lot.
The patches are still necessary, and Steam Deck hack is still necessary for SteamOS Stable (however it's not necessary for Beta).

Update to 5.0-17995

---

org.DolphinEmu.dolphin-emu.yml

With the release of SteamOS 3.4 it's no longer necessary: https://steamcommunity.com/games/1675200/announcements/detail/3646258449514531839.

Remove Steam Deck filepicker hack

---

org.DolphinEmu.dolphin-emu.yml

freedesktop 22.08 adds bluez (`libbluetooth.so`)
I was trying to figure out some flatpak bluetooth stuff when I found my old comment https://github.com/flathub/org.DolphinEmu.dolphin-emu/pull/70#issuecomment-856052201
> I would have thought bluez libs would be available in one of the freedesktop runtimes, not sure how to conveniently check for this.
I have since figured out how to conveniently check this:
```bash
diff <(flatpak run --system --command=find org.freedesktop.Platform//21.08 /usr -name '*bluetooth*') \
<(flatpak run --system --command=find org.freedesktop.Platform//22.08 /usr -name '*bluetooth*')
```
```diff
0a1,2
> /usr/lib/x86_64-linux-gnu/libbluetooth.so.3
> /usr/lib/x86_64-linux-gnu/libbluetooth.so.3.19.8
```

Use platform bluez

---

org.DolphinEmu.dolphin-emu.yml

Is there any reason for this line?
When I build most flatpak packages locally I can run them with `flatpak run org.DolphinEmu.dolphin-emu//master`.
With this repo I have to make sure the `flatpak-builder` command includes a `--user` so it doesn't complain that `org.DolphinEmu.dolphin-emu//stable` is already installed.

Remove branch field

---

org.DolphinEmu.dolphin-emu.yml

I encounter this error every time I launch a Dolphin game through Steam Deck's Game Mode UI:
I've encountered it many times before when launching games through other Flatpaks, like those for Lutris, Heroic, and other emulators. Recently, I found that this error went away after adding support for HDR on Steam Deck to [Lutris Flatpak](https://github.com/flathub/net.lutris.Lutris/commit/3ec57b415882054d06668911aaa73761dfd47d14) -- itself based on the method used for enabling HDR support on [Heroic](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3281#issuecomment-1886180726) and [Chiaki4deck](https://github.com/streetpea/chiaki4deck/issues/93#issuecomment-1830897848). So I'm pushing this PR that I believe will give Dolphin Flatpak access to the Gamescope socket. I'm …

Grant access to Gamescope socket on Steam Deck

---

org.DolphinEmu.dolphin-emu.appdata.xml
org.DolphinEmu.dolphin-emu.yml

Creating the beta branch in order to reconcile #198 and #203.
- The users who want #198 will be able to by using the beta branch.

Update beta branch to 2407-103

---

org.DolphinEmu.dolphin-emu.appdata.xml
org.DolphinEmu.dolphin-emu.yml

This reverts commit 9ecb23d1cd3a21b5e8edbf34316a18c4f54862b1.
Fixes #203, #204.
Retroachievements support is available on flathub-beta.

Revert "Bump to dev for RetroAchievements support"

---

flathub.json

The beta branch is redundant now that there are official dev builds from the dolphin ci.

Mark beta branch as eol

---

README.md
org.DolphinEmu.dolphin-emu.yml

The shim is no longer needed, dolphin handles all the cases directly over dbus.
On current versions of kde and gnome this works through the portal without any issues, but permissions have been added in order to handle older versions and desktops were the portal isn't available or doesn't work properly.

screensaver inhibition: drop shim and add permissions for older systems
